# -*- coding: utf-8 -*-
"""
Automatically generated by Colaboratory.

Original files are located at
    https://colab.research.google.com/drive/1jCNCB3Y-kLGvlVyVChoz9wj1PbmqiM14
    https://colab.research.google.com/drive/1794pBBGK_8l1wBG2Zj_BaE0vUxW3tM5K

This notebook will 
(1) create a geoJSON layer of hex bins clipped to Guatemala 
(2) read data from the Activity Location Data template and replace the exact site location data with a H3 hexagon.

Update the `ald_file` variable to the path to the Activity Location Data template
"""

import pandas as pd
import geopandas as gpd
import h3pandas  ## adds h3 methods to pandas dataframe
from shapely import wkt
from shapely.geometry import Point, Polygon

# file locations
ald_file = 'UPDATE_FILE_NAME'

# hex grid 
gdf = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
gdf = gdf.loc[gdf['name'].eq('Guatemala')]
resolution = 6

# Resample to H3 cells
hex_df = gdf.h3.polyfill_resample(resolution)

# output H3 grid
hex_df.geometry.to_file("gtm-hex-6.geojson", driver='GeoJSON')

# read activity location data
df = pd.read_csv(ald_file, encoding='utf-8')
df = df.dropna(axis=0, subset=['Latitude*', 'Longitude*'])
gdf = gpd.GeoDataFrame(df, geometry = [Point(xy) for xy in zip(df['Longitude*'], df['Latitude*'])], crs=4326)

# get grid numbers
gdf_hex = gdf.h3.geo_to_h3(resolution)
df_hex_out = gdf_hex.drop(['Latitude*', 'Longitude*', 'geometry'], axis=1)

# output activity location data
df_hex_out.to_csv('activity-location-by-hex.csv', encoding='utf-8')